# Generated by Django 5.0.4 on 2024-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='superadmin.services'),
        ),
    ]
