# Generated by Django 5.0.4 on 2024-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_events_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='event_img'),
        ),
    ]
