# Generated by Django 5.0.4 on 2024-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_events_description_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='services'),
        ),
    ]
