# Generated by Django 5.0.4 on 2024-06-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
