# Generated by Django 5.0.4 on 2024-06-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_alter_managers_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendorservices',
        ),
    ]
