# Generated by Django 5.0.4 on 2024-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_delete_vendorservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='venue pictures'),
        ),
    ]
