# Generated by Django 5.0.4 on 2024-06-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
