# Generated by Django 5.0.4 on 2024-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_booking_customer'),
        ('vendors', '0004_vendorservices_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, to='vendors.vendorservices'),
        ),
    ]
