# Generated by Django 5.0.4 on 2024-06-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_services_image'),
        ('user', '0007_booking_manager_alter_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superadmin.events'),
            preserve_default=False,
        ),
    ]
