# Generated by Django 5.0.4 on 2024-06-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_events_description_events_image'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendorservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.location')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.services')),
            ],
        ),
    ]
