# Generated by Django 5.0.4 on 2024-06-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorservices',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendors'),
        ),
    ]
