# Generated by Django 5.0.4 on 2024-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorservices_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservices',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
